Some changes
JimmyLv/BibiGPT pull request #57
Opened 2023-03-18 18:21 UTC by conglinyizhi

- Fix the problem of not being able to install with `pnpm install` (fixed by installing several packages)
- Adding a few TypeScript comments will help more with syntax hints in the editor
- Try to make a click-to-copy switch function and turn it off with default (for the time being, it will be operated with a button, but we will consider using the `Switch` component instead) and test it locally
-  A configuration was added to the `.gitignore` file to tell git to ignore pnpm's locked files

In the future, can I fill in information in Chinese? Just when submitting a pull request. As Chinese can better express my intentions, English may lead to semantic bias, I look forward to your reply.

2023-03-19 02:57 UTC, JimmyLv requested changes
sure, you can use Chinese. by the way, could you please change the PR title by following the https://semver.org/?

Also, the location of this button, expect it can be placed elsewhere 😁 deployment here: https://chat-bilibili-video-6xhd7kab2-jimmy-lv-s-team.vercel.app/

![Google Chrome-httpschat-bilibili-video-6xhd7kab2-jimmy-lv-s-team vercel app-001747-20230319](https://user-images.githubusercontent.com/4997466/226151106-2a726610-2e5f-42d9-bc8c-64a1643e2586.png)

2023-03-19 03:07 UTC, conglinyizhi commented
好的，我会尽快应用这些修改

2023-03-19 05:42 UTC, conglinyizhi commented
完成，按钮已经更换为一个基于 `Swicth` 组建封装的 `SwicthItem` 并且更换了放置位置。

我不认为新增一个开关是新的功能，因此，我没有增加次版本号

2023-03-19 07:05 UTC, JimmyLv requested changes
PR的标题用于描述功能，比如 feat: add copy switch button 或 fix: support pnpm 
最终会变成一个  git commit，这个 版本号不用你自己操作的，由 GitHub Action 自动生成。
另外麻烦把一些没必要的代码注释去掉哇， // thanks

2023-03-19 08:06 UTC, conglinyizhi commented
> PR的标题用于描述功能，比如 feat: add copy switch button 或 fix: support pnpm 最终会变成一个 git commit，这个 版本号不用你自己操作的，由 GitHub Action 自动生成。 另外麻烦把一些没必要的代码注释去掉哇， // thanks

我已经修改了 PR 的标题，但是我不清楚您描述的“没必要的代码”指的是哪些，是类似图片中的这种可以让编辑器展示更多提示的注释吗？
- 如果是，我在未来的提交中可以尽可能不放置这些注释
- 或者，您是说在 `hooks/notes/lark.ts` 中的 `but why` 注释？这个注释的原因是我目前不明白传入的数据中会多出来一个换行符，这个开头的换行符会导致问题 #54 ，所以我在某次修改的时候加入了这一行注释，考虑到这行注释可能会对其他贡献者产生麻烦，我也可以删除。

期待您的回复。

![图片](https://user-images.githubusercontent.com/42381347/226161936-1a7efbbd-fe29-4c74-b381-bbcd1418d57a.png)

2023-03-19 16:10 UTC, JimmyLv requested changes
辛苦再修改一下下

2023-03-19 16:10 UTC, JimmyLv commented on components/ActionsAfterResult.tsx
> +  // const [clickCopy, setClickCopy] = useLocalStorage<boolean>('user-config-clickCopy') || false
哈哈哈 我指的这个啦

2023-03-19 16:10 UTC, JimmyLv commented on components/SummaryResult.tsx
> +// import { Switch as SwitchItem } from './ui/switch'
here

2023-03-19 16:10 UTC, JimmyLv commented on components/SummaryResult.tsx
> +        onClick={clickCopyTest}
xxxTest 可不是好的名字

2023-03-19 16:10 UTC, JimmyLv commented on hooks/notes/lark.ts
> +                    tag: 'text',
其实可以用'markdown' 你看看飞书的文档哇？

2023-03-20 00:13 UTC, conglinyizhi commented
好的，我会尽快修改，很抱歉我有一个差劲的编码习惯

对于 markdown 我在用过几次功能后的确有类似的想法，在删除那些注释后我会加上的

丛林意志 使用 Outlook
________________________________
From: JimmyLv_吕立青 ***@***.***>
Sent: Monday, March 20, 2023 12:10:25 AM
To: JimmyLv/BibiGPT ***@***.***>
Cc: conglinyizhi ***@***.***>; Author ***@***.***>
Subject: Re: [JimmyLv/BibiGPT] fix: support pnpm (PR #57)


@JimmyLv requested changes on this pull request.

辛苦再修改一下下

________________________________

In components/ActionsAfterResult.tsx<https://github.com/JimmyLv/BibiGPT/pull/57#discussion_r1141402743>:

> @@ -19,6 +19,7 @@ export function ActionsAfterResult({
   const { loading: flomoLoading, save: flomoSave } = useSaveToFlomo(summaryNote, flomoWebhook || '')
   const { loading: larkLoading, save: larkSave } = useSaveToLark(summaryNote, larkWebhook || '')
   const hasNoteSetting = flomoWebhook || larkWebhook
+  // const [clickCopy, setClickCopy] = useLocalStorage<boolean>('user-config-clickCopy') || false


哈哈哈 我指的这个啦

________________________________

In components/SummaryResult.tsx<https://github.com/JimmyLv/BibiGPT/pull/57#discussion_r1141402774>:

>  import { formatSummary } from '~/utils/formatSummary'
+// import { Switch as SwitchItem } from './ui/switch'


here

________________________________

In components/SummaryResult.tsx<https://github.com/JimmyLv/BibiGPT/pull/57#discussion_r1141402918>:

>        <div
         className="mx-auto mt-6 max-w-3xl cursor-copy rounded-xl border-2 bg-white p-4 text-lg leading-7 shadow-md transition hover:bg-gray-50"
-        onClick={handleCopy}
+        onClick={clickCopyTest}


xxxTest 可不是好的名字

________________________________

In hooks/notes/lark.ts<https://github.com/JimmyLv/BibiGPT/pull/57#discussion_r1141403072>:

>          content: {
-          text: `${note} \n BibiGPT`,
+          post: {
+            zh_cn: {
+              title: 'BibiGPT 总结',
+              content: [
+                [
+                  {
+                    tag: 'text',


其实可以用'markdown' 你看看飞书的文档哇？

―
Reply to this email directly, view it on GitHub<https://github.com/JimmyLv/BibiGPT/pull/57#pullrequestreview-1347500444>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AKDLAI2AKCACVDXETP4FDLTW44VXDANCNFSM6AAAAAAV7TQFW4>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-03-21 01:47 UTC, JimmyLv approved these changes

2023-03-21 01:47 UTC, merged